//
//  CreateEditEntryViewController.swift
//  GeoMemories
//
//  Created by Арсен Саруханян on 20.08.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SnapKit
import MapKit
import Combine

// MARK: - View Protocol
protocol CreateEditEntryDisplayLogic: AnyObject {
    func configureNavigationBarTitle(viewModel: CreateEditEntry.ConfigurePurpose.ViewModel)
    func displayLocationSearchResults(viewModel: CreateEditEntry.SearchLocation.ViewModel)
    func displaySelectedLocation(viewModel: CreateEditEntry.ChooseLocation.ViewModel)
    func detintCurrentLocationButton()
}

// MARK: - View Controller
class CreateEditEntryViewController: UIViewController {
    var interactor: CreateEditEntryBusinessLogic?
    var router: (NSObjectProtocol & CreateEditEntryRoutingLogic & CreateEditEntryDataPassing)?
    
    private var searchTimer: Timer?
    private var didSelectLocationProgrammatically = false
    private var locationRows: [LocationCellViewModelProtocol] = []
    
    // MARK: - UI Components
    
    private lazy var locationSearchTextField: RoundedCornersTextField = {
        let textField = RoundedCornersTextField()
        textField.placeholder = String(localized: "locationSearchFieldPlaceholder")
        textField.backgroundColor = .black.withAlphaComponent(0.1)
        textField.rightView = currentLocationButton
        textField.rightViewMode = .unlessEditing
        textField.clearButtonMode = .whileEditing
        textField.returnKeyType = .search
        return textField
    }()
    
    private let currentLocationButton: UIButton = {
        var config = UIButton.Configuration.plain()
        config.image = UIImage(systemName: "location.fill")
        config.buttonSize = .mini
        
        let button = UIButton(configuration: config)
        button.tintColor = .systemGray
        return button
    }()
    
    private let searchResultsTableView: UITableView = {
        let tableView = UITableView()
        tableView.backgroundColor = .clear
        tableView.separatorStyle = .singleLine
        tableView.showsVerticalScrollIndicator = false
        return tableView
    }()
    
    private let locationSearchContrainer: UIView = {
        let view = UIView()
        view.backgroundColor = .black.withAlphaComponent(0.1)
        if #available(iOS 26.0, *) {
            view.cornerConfiguration = .corners(radius: .containerConcentric())
        } else {
            view.layer.cornerRadius = 16
        }
        view.clipsToBounds = true
        view.layer.masksToBounds = true
        view.isHidden = true
        return view
    }()
    
    private let searchActivityIndicator: UIActivityIndicatorView = {
        let indicator = UIActivityIndicatorView(style: .large)
        indicator.hidesWhenStopped = true
        return indicator
    }()
    
    private let entryTitleTextField: RoundedCornersTextField = {
        let textField = RoundedCornersTextField()
        textField.placeholder = String(localized: "geoEntryTitleTextFieldPlaceholder")
        textField.backgroundColor = .black.withAlphaComponent(0.1)
        textField.layer.cornerRadius = 16
        textField.clearButtonMode = .whileEditing
        textField.returnKeyType = .next
        return textField
    }()
    
    private let entryDescriptionContainerView: UIView = {
        let view = UIView()
        view.layer.cornerRadius = 16
        view.layer.masksToBounds = true
        view.backgroundColor = .black.withAlphaComponent(0.1)
        return view
    }()
    
    private let placeholderContainerView: UIView = UIView()
    
    private let entryDescriptionPlaceholderLabel: UILabel = {
        let label = UILabel()
        label.text = String(localized: "geoEntryDescriptionTextFieldPlaceholder")
        label.font = .systemFont(ofSize: 14)
        label.numberOfLines = 0
        label.layer.masksToBounds = true
        
        return label
    }()
    
    private lazy var entryDescriptionTextView: UITextView = {
        let textView = UITextView()
        textView.backgroundColor = .clear
        textView.textContainerInset = .zero
        textView.font = .systemFont(ofSize: 17)
        textView.returnKeyType = .done
        return textView
    }()
    
    private let addImageButton: UIButton = {
        var config = UIButton.Configuration.borderedTinted()
        // TODO: - localize stuff
        config.title = "Take image / Add image from gallery"
        config.image = UIImage(systemName: "camera")
        config.imagePlacement = .top
        config.imagePadding = 8
        
        let button = UIButton(configuration: config)
        button.tintColor = .systemGray
        return button
    }()
    
    private let addVideoButton: UIButton = {
        var config = UIButton.Configuration.borderedTinted()
        // TODO: - localize stuff
        config.title = "Take video / Add video from gallery"
        config.image = UIImage(systemName: "video")
        config.imagePlacement = .top
        config.imagePadding = 8
        
        let button = UIButton(configuration: config)
        button.tintColor = .systemGray
        return button
    }()
    
    // MARK: View lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
        setupUI()
    }
    
    override func touchesBegan(_ touches: Set<UITouch>, with event: UIEvent?) {
        view.endEditing(true)
    }
}

// MARK: - Animation Methods
private extension CreateEditEntryViewController {
    func showSearchContainer(with height: CGFloat) {
        locationSearchContrainer.isHidden = false
        
        locationSearchContrainer.snp.updateConstraints { make in
            make.height.equalTo(height)
        }
        
        UIView.animate(withDuration: 0.3, delay: 0, usingSpringWithDamping: 0.8, initialSpringVelocity: 0) {
            self.view.layoutIfNeeded()
        }
    }
    
    func hideSearchContainer() {
        locationSearchContrainer.isHidden = true
        
        locationSearchContrainer.snp.updateConstraints { make in
            make.height.equalTo(0)
        }
        
        UIView.animate(withDuration: 0.3, delay: 0, usingSpringWithDamping: 0.8, initialSpringVelocity: 0) {
            self.view.layoutIfNeeded()
        } completion: { _ in
            self.locationSearchContrainer.isHidden = true
        }
    }
}

// MARK: - UI Setup
private extension CreateEditEntryViewController {
    func setupUI() {
        interactor?.provideNavigationBarTitle()
        
        navigationItem.rightBarButtonItem = UIBarButtonItem(
            barButtonSystemItem: .cancel,
            target: self,
            action: #selector(dismissSheet)
        )
        
        currentLocationButton.addTarget(
            self,
            action: #selector(currentLocationButtonDidTap),
            for: .touchUpInside
        )
        
        locationSearchTextField.delegate = self
        entryTitleTextField.delegate = self
        //entryDescriptionTextField.delegate = self
        
        locationSearchTextField.addTarget(
            self,
            action: #selector(handleLocationSearchTextChange),
            for: .editingChanged
        )
        
        searchResultsTableView.delegate = self
        searchResultsTableView.dataSource = self
        searchResultsTableView.register(
            LocationCellView.self,
            forCellReuseIdentifier: LocationCellView.reuseIdentifier
        )
        
        // FIXME: - Might not be necessary
        searchActivityIndicator.center = searchResultsTableView.center
        
        setupConstraints()
    }
    
    func setupConstraints() {
        view.addSubview(locationSearchTextField)
        locationSearchContrainer.addSubview(searchResultsTableView)
        view.addSubview(locationSearchContrainer)
        view.bringSubviewToFront(locationSearchTextField)
        
        view.addSubview(entryTitleTextField)
        view.addSubview(entryDescriptionContainerView)
        placeholderContainerView.addSubview(entryDescriptionPlaceholderLabel)
        entryDescriptionContainerView.addSubview(placeholderContainerView)
        entryDescriptionContainerView.addSubview(entryDescriptionTextView)
        
        let mediaStackView = UIStackView(arrangedSubviews: [addImageButton, addVideoButton])
        mediaStackView.axis = .horizontal
        mediaStackView.spacing = 16
        mediaStackView.alignment = .fill
        mediaStackView.distribution = .fillEqually
        view.addSubview(mediaStackView)
        
        // FIXME: - to be removed
        if #available(iOS 26.0, *) {
            locationSearchTextField.cornerConfiguration = .corners(radius: .containerConcentric())
        } else {
            locationSearchTextField.layer.cornerRadius = 16
        }
        
        locationSearchTextField.snp.makeConstraints { make in
            make.leading.equalToSuperview().offset(16)
            make.trailing.equalToSuperview().offset(-16)
            make.top.equalTo(view.safeAreaLayoutGuide.snp.top)
            make.height.equalTo(44)
        }
        
        locationSearchContrainer.snp.makeConstraints { make in
            make.leading.trailing.equalTo(locationSearchTextField)
            make.top.equalTo(locationSearchTextField.snp.bottom).offset(-48)
            make.height.equalTo(0)
        }
        
        searchResultsTableView.snp.makeConstraints { make in
            make.edges.equalToSuperview().inset(
                UIEdgeInsets(
                    top: 48,
                    left: 0,
                    bottom: 0,
                    right: 0
                )
            )
        }
        
        entryTitleTextField.snp.makeConstraints { make in
            make.top.equalTo(locationSearchTextField.snp.bottom).offset(16)
            make.leading.trailing.equalToSuperview().inset(16)
            make.height.equalTo(44)
        }
        
        entryDescriptionContainerView.snp.makeConstraints { make in
            make.top.equalTo(entryTitleTextField.snp.bottom).offset(16)
            make.leading.trailing.equalToSuperview().inset(16)
            make.height.equalTo(192)
        }
        
        placeholderContainerView.snp.makeConstraints { make in
            make.height.equalTo(36)
            make.leading.top.trailing.equalToSuperview()
        }
        
        entryDescriptionPlaceholderLabel.snp.makeConstraints { make in
            make.leading.trailing.equalToSuperview().inset(16)
            make.top.bottom.equalToSuperview()
        }
        
        entryDescriptionTextView.snp.makeConstraints { make in
            make.top.equalTo(placeholderContainerView.snp.bottom)
            make.leading.trailing.equalToSuperview().inset(16)
            make.bottom.equalToSuperview()
        }
        
        mediaStackView.snp.makeConstraints { make in
            make.leading.trailing.equalToSuperview().inset(16)
            make.top.equalTo(entryDescriptionTextView.snp.bottom).offset(16)
            make.height.equalTo(96)
        }
    }
    
    func showAlert(with title: String, message: String, performing actions: [UIAlertAction] = []) {
        let alertController = UIAlertController(
            title: title,
            message: message,
            preferredStyle: .alert
        )
        actions.forEach { alertController.addAction($0) }
        alertController.addAction(
            UIAlertAction(
                title: String(localized: "ok"),
                style: .default
            )
        )
        present(alertController, animated: true)
    }
}

// MARK: - Private selector methods
@objc private extension CreateEditEntryViewController {
    func dismissSheet() {
        dismiss(animated: true)
    }
    
    func handleLocationSearchTextChange(_ textField: UITextField) {
        switch textField {
        case locationSearchTextField:
            searchTimer?.invalidate()
            
            guard let text = textField.text,
                  !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
                currentLocationButton.tintColor = .systemGray
                interactor?.provideLocationSearchResults(request: .clear)
                return
            }
            
            #if DEBUG
            searchTimer = Timer.scheduledTimer(
                withTimeInterval: 2,
                repeats: false,
                block: { [weak self] _ in
                    self?.interactor?.provideLocationSearchResults(request: .search(query: text))
                }
            )
            #else
            searchTimer = Timer.scheduledTimer(
                withTimeInterval: 1,
                repeats: false,
                block: { [weak self] _ in
                    self?.interactor?.provideLocationSearchResults(request: .search(query: text))
                }
            )
            #endif
        case entryTitleTextField:
            break
        case entryDescriptionTextView:
            break
        default:
            fatalError("Unimplemented text field: \(textField)")
        }
    }
    
    func currentLocationButtonDidTap() {
        currentLocationButton.tintColor = .systemBlue
        interactor?.selectLocation(request: .current)
    }
}

// MARK: - UITextFieldDelegate
extension CreateEditEntryViewController: UITextFieldDelegate {
    func textFieldDidBeginEditing(_ textField: UITextField) {
        switch textField {
        case locationSearchTextField:
            if let text = textField.text,
               !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
                interactor?.provideLocationSearchResults(request: .search(query: text))
            }
        case entryTitleTextField:
            break
        case entryDescriptionTextView:
            break
        default:
            fatalError("Unimplemented text field: \(textField)")
        }
    }
    
    func textFieldShouldEndEditing(_ textField: UITextField) -> Bool {
        switch textField {
        case locationSearchTextField:
            if !didSelectLocationProgrammatically {
                interactor?.provideLocationSearchResults(request: .cancelled)
            } else {
                didSelectLocationProgrammatically = false
            }
        case entryTitleTextField:
            break
        case entryDescriptionTextView:
            break
        default:
            fatalError("Unimplemented text field: \(textField)")
        }
        return true
    }
    
    func textFieldShouldClear(_ textField: UITextField) -> Bool {
        switch textField {
        case locationSearchTextField:
            interactor?.provideLocationSearchResults(request: .clear)
        case entryTitleTextField:
            break
        case entryDescriptionTextView:
            break
        default:
            fatalError("Unimplemented text field: \(textField)")
        }
        return true
    }
}

// MARK: - UITableViewDataSource
extension CreateEditEntryViewController: UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        locationRows.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cellViewModel = locationRows[indexPath.row]
        guard let cell = tableView.dequeueReusableCell(
            withIdentifier: LocationCellView.reuseIdentifier,
            for: indexPath
        ) as? LocationCellView else {
            return UITableViewCell()
        }
        cell.viewModel = cellViewModel
        return cell
    }
}

// MARK: - UITableViewDelegate
extension CreateEditEntryViewController: UITableViewDelegate {
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        locationRows[indexPath.row].height
    }
    
    func tableView(_ tableView: UITableView, willSelectRowAt indexPath: IndexPath) -> IndexPath? {
        let viewModel = locationRows[indexPath.row]
        return viewModel.isSelectable ? indexPath : nil
    }
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        tableView.deselectRow(at: indexPath, animated: true)
        let row = locationRows[indexPath.row]
        interactor?.selectLocation(request: .manual(row: row))
    }
}

// MARK: - CreateEditEntryDisplayLogic
extension CreateEditEntryViewController: CreateEditEntryDisplayLogic {
    func configureNavigationBarTitle(viewModel: CreateEditEntry.ConfigurePurpose.ViewModel) {
        title = viewModel.title
        // FIXME: - do not put this into this method, this is just for testing
        navigationItem.leftBarButtonItem = UIBarButtonItem(systemItem: .save)
    }
    
    func displayLocationSearchResults(
        viewModel: CreateEditEntry.SearchLocation.ViewModel
    ) {
        didSelectLocationProgrammatically = false
        
        switch viewModel {
        case .loading:
            searchActivityIndicator.startAnimating()
            locationRows = []
        case .success(let results):
            searchActivityIndicator.stopAnimating()
            locationRows = results
            showSearchContainer(with: results.map(\.height).reduce(0, +) + 48)
            searchResultsTableView.reloadData()
        case .userCancelled:
            searchActivityIndicator.stopAnimating()
            locationRows = []
            searchResultsTableView.reloadData()
            hideSearchContainer()
        case .failure(let alertTitle, let alertMessage):
            searchActivityIndicator.stopAnimating()
            locationRows = []
            searchResultsTableView.reloadData()
            hideSearchContainer()
            showAlert(with: alertTitle, message: alertMessage)
        }
    }
    
    func displaySelectedLocation(viewModel: CreateEditEntry.ChooseLocation.ViewModel) {
        didSelectLocationProgrammatically = true
        view.endEditing(true)
        
        switch viewModel {
        case .success(let description):
            locationSearchTextField.text = description
        case .none:
            locationSearchTextField.text = nil
        case .failure(let alertTitle, let alertMessage):
            showAlert(with: alertTitle, message: alertMessage)
        }
    }
    
    func detintCurrentLocationButton() {
        currentLocationButton.tintColor = .systemGray
    }
}
