//
//  CreateEditEntryModels.swift
//  GeoMemories
//
//  Created by Арсен Саруханян on 20.08.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import MapKit

// swiftlint:disable nesting
enum CreateEditEntry {
    // MARK: Use cases
    enum ConfigurePurpose {
        struct Response {
            let isEditMode: Bool
        }
        
        struct ViewModel {
            let title: String
        }
    }
    
    enum SearchLocation {
        enum Request {
            case clear
            case cancelled
            case search(query: String)
        }
        
        enum Response {
            case loading
            case success(results: [MKMapItem])
            case failure(error: Error)
            case userCancelled
        }
        
        enum ViewModel {
            case loading
            case success(results: [LocationCellViewModelProtocol])
            case userCancelled
            case failure(alertTitle: String, alertMessage: String)
        }
    }
    
    enum LoadExistingEntry {
        
    }
    
    enum ChangeEntryTitle {
        struct Response {
            
        }
        
        struct ViewModel {
            
        }
    }
    
    enum ChangeDescription {
        
    }
    
    enum ChooseLocation {
        enum Request {
            case abort
            case manual(row: LocationCellViewModelProtocol)
            case current
        }
        
        enum Response {
            case empty
            case successWithSelectedLocation(mapItem: MKMapItem)
            case successWithCurrentLocation(location: CLLocation)
            case failure(error: LocationError)
        }
        
        enum ViewModel {
            case success(description: String)
            case failure(alertTitle: String, alertMessage: String)
            case none
        }
    }
    
    enum AddPhoto {
        
    }
    
    enum AddVideo {
        
    }
    
    enum DeleteMedia {
        
    }
    
    enum Save {
        
    }
}
