//
//  CreateEditEntryInteractor.swift
//  GeoMemories
//
//  Created by Арсен Саруханян on 20.08.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

protocol CreateEditEntryBusinessLogic {
    func provideNavigationBarTitle()
}

protocol CreateEditEntryDataStore {
    var entry: GeoEntry? { get set }
}

class CreateEditEntryInteractor: CreateEditEntryBusinessLogic, CreateEditEntryDataStore {
    var entry: GeoEntry?
    
    var presenter: CreateEditEntryPresentationLogic?
    var worker: CreateEditEntryWorker?
    
    func provideNavigationBarTitle() {
        let response = CreateEditEntry.ConfigurePurpose.Response(isEditMode: entry == nil)
        presenter?.presentNavigationBarTitle(response: response)
    }
}
