//
//  CreateEditEntryRouter.swift
//  GeoMemories
//
//  Created by Арсен Саруханян on 20.08.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CreateEditEntryRoutingLogic {
    
}

protocol CreateEditEntryDataPassing {
    var dataStore: CreateEditEntryDataStore? { get }
}

class CreateEditEntryRouter: NSObject, CreateEditEntryRoutingLogic, CreateEditEntryDataPassing {
    
    weak var viewController: CreateEditEntryViewController?
    var dataStore: CreateEditEntryDataStore?
}
