//
//  CreateEditEntryPresenter.swift
//  GeoMemories
//
//  Created by Арсен Саруханян on 20.08.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

protocol CreateEditEntryPresentationLogic {
    func presentNavigationBarTitle(response: CreateEditEntry.ConfigurePurpose.Response)
}

class CreateEditEntryPresenter: CreateEditEntryPresentationLogic {
    weak var viewController: CreateEditEntryDisplayLogic?
    
    func presentNavigationBarTitle(response: CreateEditEntry.ConfigurePurpose.Response) {
        let title = String(localized: response.isEditMode ? "editingTitle" : "creatingTitle")
        let viewModel = CreateEditEntry.ConfigurePurpose.ViewModel(title: title)
        viewController?.configureNavigationBarTitle(viewModel: viewModel)
    }
}
