//
//  CreateEditEntryModels.swift
//  GeoMemories
//
//  Created by Арсен Саруханян on 20.08.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

// swiftlint:disable nesting
enum CreateEditEntry {
    // MARK: Use cases
    enum ConfigurePurpose {
        struct Response {
            let isEditMode: Bool
        }
        
        struct ViewModel {
            let title: String
        }
    }
    
    enum LoadExistingEntry {
        
    }
    
    enum ChangeEntryTitle {
        struct Response {
            
        }
        
        struct ViewModel {
            
        }
    }
    
    enum ChangeDescription {
        
    }
    
    enum ChooseManualLocation {
        struct Request {
            
        }
        
        struct Response {
            
        }
        
        struct ViewModel {
            
        }
    }
    
    enum ChooseCurrentLocation {
        
    }
    
    enum AddPhoto {
        
    }
    
    enum AddVideo {
        
    }
    
    enum DeleteMedia {
        
    }
    
    enum Save {
        
    }
}
