//
//  SearchLocationContainerModels.swift
//  GeoMemories
//
//  Created by Арсен Саруханян on 24.08.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import MapKit
import CoreLocation

// swiftlint:disable nesting
enum SearchLocationContainer {
    // MARK: Use cases
    enum SearchLocation {
        enum Request {
            case clear
            case cancelled(userInitiated: Bool)
            case search(query: String)
        }
        
        enum Response {
            case success(results: [MKMapItem])
            case failure(error: LocationError)
            case userCancelled(shouldClearTextField: Bool)
        }
        
        enum ViewModel {
            case success(results: [LocationCellViewModelProtocol])
            case userCancelled
            case failure(alertTitle: String, alertMessage: String)
        }
    }
    
    enum ChooseLocation {
        enum Request {
            case manual(row: LocationCellViewModelProtocol)
            case current
        }
        
        enum Response {
            case empty
            case successWithSelectedLocation(mapItem: MKMapItem)
            case successWithCurrentLocation(location: CLLocation)
            case failure(error: LocationError)
        }
        
        enum ViewModel {
            case success(description: String)
            case failure(alertTitle: String, alertMessage: String)
            case none
        }
    }
}
