//
//  SearchLocationContainerRouter.swift
//  GeoMemories
//
//  Created by Арсен Саруханян on 24.08.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SearchLocationContainerRoutingLogic {
}

protocol SearchLocationContainerDataPassing {
    var dataStore: SearchLocationContainerDataStore? { get }
}

class SearchLocationContainerRouter: NSObject, SearchLocationContainerRoutingLogic, SearchLocationContainerDataPassing {
    
    weak var viewController: SearchLocationContainerViewController?
    var dataStore: SearchLocationContainerDataStore?
}
