//
//  HomeViewController.swift
//  GeoMemories
//
//  Created by Арсен Саруханян on 18.08.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SnapKit
import MapKit

protocol HomeDisplayLogic: AnyObject {
    func displayCurrentLocation(viewModel: Home.SelectCurrentLocation.ViewModel)
    #warning("Make annotations, popups for annotations, add new entry functionality and show details functionality")
    func displayMapEntries(viewModel: Home.ShowMapEntries.ViewModel)
}

class HomeViewController: UIViewController {
    let defaultPinIdentifier = "DefaultPin"
    
    var interactor: HomeBusinessLogic?
    var router: (NSObjectProtocol & HomeRoutingLogic & HomeDataPassing)?
    
    private let mapView: MKMapView = {
        let map = MKMapView()
        map.showsUserLocation = true
        return map
    }()
    
    private lazy var activityIndicator: UIActivityIndicatorView = {
        let indicator = UIActivityIndicatorView(style: .large)
        indicator.hidesWhenStopped = true
        indicator.center = view.center
        return indicator
    }()
    
    // MARK: View lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
        setupUI()
    }
}

// MARK: - MKMapViewDelegate
extension HomeViewController: MKMapViewDelegate {
    func mapView(
        _ mapView: MKMapView,
        viewFor annotation: any MKAnnotation
    ) -> MKAnnotationView? {
        if let memoryAnnotation = annotation as? MemoryAnnotation {
            let identifier = MemoryAnnotationView.reuseIdentifier
            var view = mapView.dequeueReusableAnnotationView(
                withIdentifier: identifier
            )
            if view == nil {
                view = MemoryAnnotationView(
                    annotation: annotation,
                    reuseIdentifier: identifier
                )
            } else {
                view?.annotation = memoryAnnotation
            }
            return view
        }
        
        return nil
    }
}

// MARK: - UI Setup
private extension HomeViewController {
    func setupToolbar() {
        let locationPinItem = UIBarButtonItem(
            image: UIImage(systemName: "location.fill"),
            style: .plain,
            target: self,
            action: #selector(locationPinToolbarButtonTapped)
        )
        
        let addItem = UIBarButtonItem(
            barButtonSystemItem: .add,
            target: self,
            action: #selector(addBarButtonTapped)
        )
        
        if #available(iOS 26.0, *) {
            toolbarItems = [.flexibleSpace(), addItem, .fixedSpace(), locationPinItem]
        } else {
            toolbarItems = [.flexibleSpace(), addItem, locationPinItem]
        }
        navigationController?.setToolbarHidden(false, animated: false)
    }
    
    func setupUI() {
        defer { setupConstraints() }
        setupToolbar()
        view.addSubview(mapView)
        interactor?.provideMapEntries()
    }
    
    func setupConstraints() {
        mapView.snp.makeConstraints { make in
            make.edges.equalToSuperview()
        }
    }
}

// MARK: - Private selector actions
@objc private extension HomeViewController {
    func locationPinToolbarButtonTapped() {
        interactor?.provideCurrentLocation()
    }
    
    func addBarButtonTapped() {
        router?.routeToCreateEditEntry(geoEntry: nil)
    }
}

// MARK: - Private methods
private extension HomeViewController {
    func showAlert(with title: String, message: String, performing actions: [UIAlertAction] = []) {
        let alertController = UIAlertController(
            title: title,
            message: message,
            preferredStyle: .alert
        )
        actions.forEach { alertController.addAction($0) }
        alertController.addAction(
            UIAlertAction(
                title: String(localized: "ok"),
                style: .default
            )
        )
        present(alertController, animated: true)
    }
}

extension HomeViewController: HomeDisplayLogic {
    func displayCurrentLocation(viewModel: Home.SelectCurrentLocation.ViewModel) {
        switch viewModel {
        case .loading:
            activityIndicator.startAnimating()
        case .success(let region):
            activityIndicator.stopAnimating()
            mapView.setRegion(region, animated: true)
        case .failure(let alertTitle, let alertMessage):
            activityIndicator.stopAnimating()
            self.showAlert(with: alertTitle, message: alertMessage)
        }
    }
    
    func displayMapEntries(viewModel: Home.ShowMapEntries.ViewModel) {
        switch viewModel {
        case .loading:
            activityIndicator.startAnimating()
        case .sucess(let annotations):
            activityIndicator.stopAnimating()
            mapView.addAnnotations(annotations)
        case .failure(let alertTitle, let alertMessage):
            activityIndicator.stopAnimating()
            self.showAlert(
                with: alertTitle,
                message: alertMessage,
                performing: [UIAlertAction(
                    title: String(localized: "retry"),
                    style: .default,
                    handler: { [weak self] _ in
                        self?.interactor?.provideMapEntries()
                    })]
            )
        }
    }
}
