//
//  HomeModels.swift
//  GeoMemories
//
//  Created by Арсен Саруханян on 18.08.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import CoreLocation

// swiftlint:disable nesting
enum Home {
    // MARK: Use cases
    enum ShowMapEntries {
        struct Request {
            
        }
        
        struct Response {
            
        }
        
        struct ViewModel {
            
        }
    }
    
    enum SelectCurrentLocation {
        struct Request {
            
        }
        
        enum Response {
            case loading
            case success(location: CLLocation)
            case failure(error: LocationError)
        }
        
        struct ViewModel {
            let locationCenter: CLLocationCoordinate2D
            let areaRadius: CLLocationDistance
        }
    }
    
    enum ShowAlert {
        struct Request {
            
        }
        
        struct Response {
            let titleKey: String
            let messageKey: String
        }
        
        struct ViewModel {
            let title: String
            let message: String
        }
    }
    
    enum AddEntry {
        struct Request {
            
        }
        
        struct Response {
            
        }
        
        struct ViewModel {
            
        }
    }
    
    enum ShowAnnotationPopover {
        struct Request {
            
        }
        
        struct Response {
            
        }
        
        struct ViewModel {
            
        }
    }
    
    enum ShowEntryDetailsScreen {
        struct Request {
            
        }
        
        struct Response {
            
        }
        
        struct ViewModel {
            
        }
    }
}
