//
//  HomeModels.swift
//  GeoMemories
//
//  Created by Арсен Саруханян on 18.08.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import CoreLocation
import MapKit

// swiftlint:disable nesting
enum Home {
    // MARK: Use cases
    enum ShowMapEntries {
        struct Response {
            
        }
        
        enum ViewModel {
            case loading
            case sucess(annotations: [MemoryAnnotation])
            case failure(alertTitle: String, alertMessage: String)
        }
    }
    
    enum SelectCurrentLocation {
        enum Response {
            case loading
            case success(location: CLLocation)
            case failure(error: LocationError)
        }
        
        enum ViewModel {
            case loading
            case success(region: MKCoordinateRegion)
            case failure(alertTitle: String, alertMessage: String)
        }
    }
    
    enum AddEntry {
        struct Request {
            
        }
        
        struct Response {
            
        }
        
        struct ViewModel {
            
        }
    }
    
    enum ShowAnnotationPopover {
        struct Request {
            
        }
        
        struct Response {
            
        }
        
        struct ViewModel {
            
        }
    }
    
    enum ShowEntryDetailsScreen {
        struct Request {
            
        }
        
        struct Response {
            
        }
        
        struct ViewModel {
            
        }
    }
}
