//
//  HomeInteractor.swift
//  GeoMemories
//
//  Created by Арсен Саруханян on 18.08.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation
import Combine
import CoreStore

protocol HomeBusinessLogic {
    func provideCurrentLocation()
    func provideMapEntries()
    func addMapEntry(request: Home.AddEntry.Request)
    func provideEntryCallout(request: Home.ShowAnnotationPopover.Request)
}

protocol HomeDataStore {
    var entries: [GeoEntry] { get }
}

class HomeInteractor: HomeBusinessLogic, HomeDataStore {
    var entries: [GeoEntry] = []
    var presenter: HomePresentationLogic?
    let worker: LocationWorker = LocationWorker()
    
    private var locationCancellable: AnyCancellable?
    
    deinit {
        locationCancellable?.cancel()
    }
    
    func provideCurrentLocation() {
        presenter?.presentCurrentLocation(response: .loading)
        
        locationCancellable = worker.getCurrentLocation()
            .receive(on: DispatchQueue.main)
            .sink(
                receiveCompletion: { [weak self] completion in
                    if case .failure(let error) = completion {
                        let response = Home.SelectCurrentLocation.Response.failure(
                            error: error
                        )
                        self?.presenter?.presentCurrentLocation(response: response)
                    }
                },
                receiveValue: { [weak self] location in
                    let response = Home.SelectCurrentLocation.Response.success(
                        location: location
                    )
                    self?.presenter?.presentCurrentLocation(response: response)
                }
            )
    }
    
    func provideMapEntries() {
        #warning("Implement next")
    }
    
    func addMapEntry(request: Home.AddEntry.Request) {
        
    }
    
    func provideEntryCallout(request: Home.ShowAnnotationPopover.Request) {
        
    }
}
