//
//  HomePresenter.swift
//  GeoMemories
//
//  Created by Арсен Саруханян on 18.08.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import CoreLocation

protocol HomePresentationLogic {
    func presentCurrentLocation(response: Home.SelectCurrentLocation.Response)
}

class HomePresenter: HomePresentationLogic {
    weak var viewController: HomeDisplayLogic?
    
    func presentCurrentLocation(response: Home.SelectCurrentLocation.Response) {
        switch response {
        case .loading:
            viewController?.displayLoadingIndicator()
        case .success(let location):
            let viewModel = Home.SelectCurrentLocation.ViewModel(
                locationCenter: location.coordinate,
                areaRadius: 1000
            )
            viewController?.displayCurrentLocation(viewModel: viewModel)
            viewController?.stopLoadingIndicator()
        case .failure(let error):
            let title: String
            let message: String
            
            if case .permissionDenied = error {
                title = String(localized: "locationServicesNotAuthorizedTitle")
                message = String(localized: "locationServicesNotAuthorizedMessage")
            } else {
                title = String(localized: "genericErrorTitle")
                message = String(localized: "noLocalizedErrorMessage") + "\n\(error.localizedDescription)"
            }
            
            let viewModel = Home.ShowAlert.ViewModel(title: title, message: message)
            viewController?.displayAlert(viewModel: viewModel)
            viewController?.stopLoadingIndicator()
        }
    }
}
